version: "3.5"

networks:
  wp:
    name: wp

services: 

  base:
    build:
      context: requirements/docker_base
    image: mbonnet/base
    container_name: cnt_base

  mariadb:
      restart: on-failure
      build:
        context: requirements/docker_mariadb
      image: mbonnet/mariadb
      container_name: cnt_mariadb
      networks:
       - wp
      volumes:
      - data_mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5

  wordpress:
    restart: on-failure
    build:
     context: requirements/docker_wordpress
    image: mbonnet/img_wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_healthy   
    networks:
      - wp
    volumes:
      - wp_volume:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_USER1: ${WORDPRESS_USER1}
      WORDPRESS_PASS1: ${WORDPRESS_PASS1}
      WORDPRESS_EMAIL1: ${WORDPRESS_EMAIL1}
      WORDPRESS_USER2: ${WORDPRESS_USER2}
      WORDPRESS_PASS2: ${WORDPRESS_PASS2}
      WORDPRESS_EMAIL2: ${WORDPRESS_EMAIL2}

  nginx:
    restart: on-failure
    build:
      context: requirements/docker_nginx/
    image : mbonnet/nginx
    container_name: cnt_nginx
    depends_on:
      - wordpress
    networks:
     - wp
    ports: 
     - "80:80"
     - "443:443"
    volumes:
      - wp_volume:/var/www/html

volumes:
  wp_volume: 
  data_mysql:


