version: "3.5"

networks:
  wp:
    name: wp

services: 

  mariadb:
      restart: on-failure
      build:
        context: docker_mariadb
      image: mbonnet/img_mariadb
      container_name: cnt_mariadb
      networks:
       - wp
      volumes:
      - data_mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5


  wordpress:
    restart: on-failure
    build:
     context: docker_wordpress
    image: mbonnet/img_wordpress
    container_name: cnt_wordpress
    depends_on:
      mariadb:
        condition: service_healthy

    networks:
      - wp
    volumes:
      - wp_volume:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE}
      WORDPRESS_URL: ${WORDPRESS_URL}



  nginx:
    restart: on-failure
    build:
      context: docker_nginx/
    image : mbonnet/img_nginx
    container_name: cnt_nginx
    depends_on:
      - wordpress
    networks:
     - wp
    ports: 
     - "80:80"
    volumes:
      - wp_volume:/var/www/html


volumes:
  wp_volume:
  data_mysql:


